# Generated by Django 5.2 on 2025-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_active",
            new_name="DangHoatDong",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="GiangVien",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="Ten",
        ),
    ]
