# Generated by Django 5.2 on 2025-04-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_is_active_user_danghoatdong_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Ten",
            new_name="name",
        ),
    ]
