# Generated by Django 5.2 on 2025-04-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_ten_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="DangHoatDong",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="GiangVien",
            new_name="is_staff",
        ),
    ]
