# Generated by Django 5.2 on 2025-04-15 05:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_danghoatdong_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AddField(
            model_name="student",
            name="student_code",
            field=models.CharField(
                default=core.models.generate_student_code, max_length=100, unique=True
            ),
        ),
    ]
