# Generated by Django 5.2 on 2025-04-15 05:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_student_student_id_student_student_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="teacher_code",
            field=models.CharField(
                default=core.models.generate_teacher_code, max_length=100, unique=True
            ),
        ),
    ]
