# Generated by Django 5.2 on 2025-04-17 13:11

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_teacher_teacher_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_code",
                    models.CharField(
                        default=core.models.generate_class_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_code",
                    models.CharField(
                        default=core.models.generate_object_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("object_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("course_name", models.CharField(max_length=100)),
                (
                    "students",
                    models.ManyToManyField(related_name="classes", to="core.student"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="class_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.classroom",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="course_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.object"
            ),
        ),
    ]
