# Generated by Django 5.2 on 2025-04-17 13:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_classroom_object_class_schedule_class_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_code",
            field=models.CharField(
                default=core.models.generate_class_code, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="classroom_code",
            field=models.CharField(
                default=core.models.generate_classroom_code, max_length=100, unique=True
            ),
        ),
    ]
