# Generated by Django 5.2 on 2025-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_class_class_code_alter_classroom_classroom_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="qr_code_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
