# Generated by Django 5.2 on 2025-04-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_schedule_qr_code_schedule_qr_code_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="course_name",
        ),
    ]
