# Generated by Django 5.2 on 2025-04-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_schedule_end_date_schedule_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Thứ 2"),
                            ("TUE", "Thứ 3"),
                            ("WED", "Thứ 4"),
                            ("THU", "Thứ 5"),
                            ("FRI", "Thứ 6"),
                            ("SAT", "Thứ 7"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="weekdays",
        ),
        migrations.AddField(
            model_name="schedule",
            name="weekdays",
            field=models.ManyToManyField(to="core.weekday"),
        ),
    ]
