# Generated by Django 5.2 on 2025-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_weekday_remove_schedule_weekdays_schedule_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teacher_classes", to="core.teacher"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teaching_classes",
            field=models.ManyToManyField(
                related_name="teaching_teachers", to="core.class"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                related_name="student_classes", to="core.student"
            ),
        ),
    ]
