# Generated by Django 5.2 on 2025-04-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_attendance_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.student"
            ),
        ),
    ]
