# Generated by Django 5.2 on 2025-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_attendance_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="minutes_late",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Vĩ độ của phòng học", null=True
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Kinh độ của phòng học", null=True
            ),
        ),
    ]
