# Generated by Django 5.2 on 2025-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_attendance_is_late_attendance_minutes_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
