# Generated by Django 5.2 on 2025-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_attendance_device_info_attendance_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="lesson_count",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Số tiết"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="lesson_start",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Tiết 1 (07:00 - 07:45)"),
                    (2, "Tiết 2 (07:50 - 08:35)"),
                    (3, "Tiết 3 (08:40 - 09:25)"),
                    (4, "Tiết 4 (09:30 - 10:15)"),
                    (5, "Tiết 5 (10:20 - 11:05)"),
                    (6, "Tiết 6 (12:45 - 13:30)"),
                    (7, "Tiết 7 (13:35 - 14:20)"),
                    (8, "Tiết 8 (14:25 - 15:10)"),
                    (9, "Tiết 9 (15:15 - 16:00)"),
                    (10, "Tiết 10 (16:05 - 16:50)"),
                    (11, "Tiết 11 (16:55 - 17:40)"),
                ],
                default=1,
                verbose_name="Tiết bắt đầu",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
