# Generated by Django 5.2 on 2025-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_schedule_lesson_count_schedule_lesson_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_in_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
